/* CONCORDVEST / Navigation: one deterministic route map keeps header, footer, breadcrumbs, and content pathways aligned across the public prototype. */
export function resolveNavigation(label: string): string | null {
  const normalized = label.trim();
  const routes: Record<string, string> = {
    Home: "/",
    "All Properties": "/properties",
    "Land for Sale": "/properties",
    Apartments: "/properties",
    "Apartments for Sale": "/properties",
    "Concordvest Property": "/properties",
    "Partner Property": "/properties",
    "Developer Listings": "/properties",
    Properties: "/properties",
    "Buy land": "/properties",
    "Buy an apartment": "/properties",
    "Renovate my property": "/services/custom-renovation",
    "Finish my property": "/services/complete-building-finishing",
    "Start a building project": "/start-building-project",
    "Start a Building Project": "/start-building-project",
    "05 — START A BUILDING PROJECT": "/start-building-project",
    "All Services": "/services",
    "Renovation & Finishing": "/services",
    "Home Refresh": "/services/home-refresh",
    "Kitchen Transformation": "/services/kitchen-transformation",
    "Bathroom Upgrade": "/services/luxury-bathroom-upgrade",
    "Luxury Bathroom Upgrade": "/services/luxury-bathroom-upgrade",
    "Building Finishing": "/services/complete-building-finishing",
    "Complete Building Finishing": "/services/complete-building-finishing",
    "Office Remodeling": "/services/office-remodeling",
    "Rental Makeover": "/services/rental-property-makeover",
    "Rental Property Makeover": "/services/rental-property-makeover",
    "Complete Remodeling": "/services/complete-home-remodeling",
    "Complete Home Remodeling": "/services/complete-home-remodeling",
    "Request a Quote": "/services/custom-renovation",
    "Book site inspection": "/services/site-inspection",
    "All Projects": "/projects",
    Projects: "/projects",
    Renovation: "/projects",
    Finishing: "/projects",
    Kitchens: "/projects",
    Bathrooms: "/projects",
    Interiors: "/projects",
    Exterior: "/projects",
    "Before & After": "/projects",
    "All Inspiration": "/inspiration",
    Inspiration: "/inspiration",
    "Home Improvement Tips": "/inspiration",
    "Kitchen Inspiration": "/inspiration",
    "Bathroom Inspiration": "/inspiration",
    "Staircase Ideas": "/inspiration",
    "Materials & Finishes": "/inspiration",
    "Construction Tips": "/inspiration",
    About: "/#about",
    Contact: "/services/custom-renovation",
  };
  return routes[normalized] || null;
}
