-- ============================================================================
-- ConcordVest Seed Data
-- ============================================================================
-- This file contains seed data for the ConcordVest application.
-- Run this AFTER running schema.sql
-- ============================================================================

-- ============================================================================
-- PROPERTIES
-- ============================================================================

INSERT INTO public.properties (id, title, slug, category, listing_type, property_type, location, area, price, bedrooms, bathrooms, land_size, building_size, description, features, amenities, documentation, availability, images, coordinates, tags, is_published) VALUES
('cv-001', 'Modern 3 Bedroom Apartment', 'modern-3-bedroom-apartment-jabi', 'Concordvest Property', 'Concordvest Property', 'Apartment', 'Jabi', 'Abuja', 185000000, 3, 4, 420, 245, 'A considered apartment with generous proportions, calm finishes, and a connected Jabi address.', ARRAY['Balcony', 'Fitted Kitchen', 'Parking'], ARRAY['Security', 'Generator', 'Water', 'Serviced Property'], ARRAY['C of O', 'Deed'], 'available', ARRAY['/manus-storage/concordvest-property_ef36ee68.jpg', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.0765, "lng": 7.4306}', ARRAY['curated', 'city living'], TRUE),
('cv-002', 'Premium Residential Land', 'premium-residential-land-katampe', 'Land for Sale', 'Developer Listing', 'Land', 'Katampe', 'Abuja', 120000000, 0, 0, 600, 0, 'A well-positioned parcel for a private residence in one of Abuja''s most considered growth corridors.', ARRAY['Security', 'Garden'], ARRAY['Water', 'Parking'], ARRAY['C of O', 'R of O'], 'available', ARRAY['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.123, "lng": 7.414}', ARRAY['land', 'residential'], TRUE),
('cv-003', 'Luxury 4 Bedroom Apartment', 'luxury-4-bedroom-apartment-wuse-2', 'Partner Property', 'Partner Property', 'Apartment', 'Wuse 2', 'Abuja', 220000000, 4, 5, 510, 330, 'A bright, private apartment with an elevated material palette and close access to Wuse 2''s daily rhythm.', ARRAY['Swimming Pool', 'Balcony', 'Fitted Kitchen', 'Smart Home'], ARRAY['Security', 'Generator', 'Water', 'Parking'], ARRAY['Deed', 'Other'], 'reserved', ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.076, "lng": 7.469}', ARRAY['luxury', 'apartment'], TRUE),
('cv-004', 'Courtyard House at Guzape', 'courtyard-house-guzape', 'Apartments for Sale', 'Concordvest Property', 'House', 'Guzape', 'Abuja', 265000000, 4, 5, 680, 390, 'A composed courtyard home designed around light, privacy, and generous outdoor living.', ARRAY['Garden', 'Swimming Pool', 'Fitted Kitchen', 'Parking'], ARRAY['Security', 'Generator', 'Water', 'Smart Home'], ARRAY['C of O', 'Deed'], 'available', ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.022, "lng": 7.495}', ARRAY['family home', 'courtyard'], TRUE),
('cv-005', 'Serviced 2 Bedroom Residence', 'serviced-2-bedroom-residence-maitama', 'Partner Property', 'Partner Property', 'Apartment', 'Maitama', 'Abuja', 148000000, 2, 3, 300, 180, 'A polished, serviced residence in a quiet Maitama setting, designed for easy city living.', ARRAY['Serviced Property', 'Balcony', 'Fitted Kitchen'], ARRAY['Security', 'Generator', 'Water', 'Parking'], ARRAY['R of O', 'Deed'], 'available', ARRAY['https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.092, "lng": 7.487}', ARRAY['serviced', 'residence'], TRUE),
('cv-006', 'Build-Ready Plot at Life Camp', 'build-ready-plot-life-camp', 'Developer Listings', 'Developer Listing', 'Land', 'Life Camp', 'Abuja', 85000000, 0, 0, 500, 0, 'A build-ready residential plot with a clear brief: space, access, and room to shape your own address.', ARRAY['Security', 'Garden'], ARRAY['Water', 'Parking'], ARRAY['R of O', 'Other'], 'sold', ARRAY['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.114, "lng": 7.39}', ARRAY['plot', 'development'], TRUE),
('cv-007', 'Garden Apartment at Asokoro', 'garden-apartment-asokoro', 'Apartments for Sale', 'Developer Listing', 'Apartment', 'Asokoro', 'Abuja', 310000000, 4, 5, 560, 360, 'An understated garden apartment with a private outdoor edge and quiet Asokoro address.', ARRAY['Garden', 'Smart Home', 'Fitted Kitchen', 'Balcony'], ARRAY['Security', 'Generator', 'Water', 'Parking'], ARRAY['C of O'], 'available', ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.034, "lng": 7.506}', ARRAY['garden', 'private'], TRUE),
('cv-008', 'Family Residence at Gwarinpa', 'family-residence-gwarinpa', 'All Properties', 'Partner Property', 'House', 'Gwarinpa', 'Abuja', 172000000, 4, 4, 540, 290, 'A practical family residence with generous rooms, reliable amenities, and room to grow.', ARRAY['Garden', 'Parking', 'Fitted Kitchen'], ARRAY['Security', 'Generator', 'Water'], ARRAY['Deed', 'Other'], 'available', ARRAY['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.101, "lng": 7.405}', ARRAY['family', 'home'], TRUE),
('cv-009', 'Courtyard Residence at Jabi', 'courtyard-residence-jabi', 'All Properties', 'Concordvest Property', 'House', 'Jabi', 'Abuja', 205000000, 3, 4, 470, 265, 'A warm courtyard residence with a practical plan, generous light, and a Jabi address.', ARRAY['Garden', 'Parking', 'Balcony'], ARRAY['Security', 'Generator', 'Water'], ARRAY['C of O', 'Deed'], 'available', ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85', 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85'], '{"lat": 9.077, "lng": 7.431}', ARRAY['courtyard', 'jabi'], TRUE);

-- ============================================================================
-- SERVICES
-- ============================================================================

INSERT INTO public.services (id, number, slug, name, short_description, overview, problems_solved, includes, process, timeline, image, related_project_image, tags, sort_order, is_published) VALUES
('svc-01', '01', 'home-refresh', 'Home Refresh', 'A precise reset for the spaces that need a lighter, cleaner point of view.', 'Home Refresh is designed for lived-in spaces that need their rhythm restored without becoming a full-scale construction site.', ARRAY['Tired finishes and marked walls', 'Small maintenance issues collecting over time', 'Spaces that feel dim, dated, or disconnected'], ARRAY['Painting', 'Minor POP repairs', 'Light replacement', 'Wall finishing', 'Door polishing', 'Basic plumbing fixes'], ARRAY['Walk-through and scope alignment', 'Surface preparation and repair', 'Finishing, polishing, and final review'], 'Timeline placeholder · typically scoped after inspection', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85', ARRAY['refresh', 'finishing', 'maintenance'], 1, TRUE),
('svc-02', '02', 'kitchen-transformation', 'Kitchen Transformation', 'A more considered kitchen through better flow, durable finishes, and everyday function.', 'Kitchen Transformation brings the working heart of the home into focus, balancing storage, surfaces, light, and the way meals actually happen.', ARRAY['Poor storage and difficult work zones', 'Worn surfaces and dated fixtures', 'Lighting and plumbing that interrupt the workflow'], ARRAY['Tiles', 'Cabinets', 'Countertops', 'Plumbing', 'Lighting', 'Sink installation'], ARRAY['Measure, brief, and material direction', 'First-fix services and cabinetry preparation', 'Installation, finishing, and handover'], 'Timeline placeholder · confirmed with scope and material lead times', 'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85', ARRAY['kitchen', 'cabinetry', 'interiors'], 2, TRUE),
('svc-03', '03', 'luxury-bathroom-upgrade', 'Luxury Bathroom Upgrade', 'A calmer daily ritual through refined surfaces, better water flow, and tactile detail.', 'Luxury Bathroom Upgrade turns a functional room into a more composed experience with careful proportion, clean detailing, and dependable services.', ARRAY['Leaking or unreliable bathroom services', 'Surfaces that are difficult to maintain', 'A bathroom that feels visually busy or under-resolved'], ARRAY['Wall tiles', 'Floor tiles', 'Shower', 'Vanity', 'Toilet', 'Water heater', 'Plumbing'], ARRAY['Site measure and design direction', 'Strip-out, service preparation, and waterproofing', 'Fit-out, detailing, and final testing'], 'Timeline placeholder · confirmed after site inspection', 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85', ARRAY['bathroom', 'tiles', 'luxury'], 3, TRUE),
('svc-04', '04', 'complete-building-finishing', 'Complete Building Finishing', 'A coordinated finishing programme for unfinished structures ready to become homes.', 'Complete Building Finishing coordinates the major finishing trades into one considered programme, reducing the friction between services and surfaces.', ARRAY['An unfinished structure without a clear sequence', 'Multiple trades working without coordination', 'Finishes that need a single quality point of view'], ARRAY['Plumbing', 'Electrical', 'POP', 'Painting', 'Tiles', 'Doors', 'Windows', 'Kitchen', 'Wardrobes'], ARRAY['Technical assessment and finishing brief', 'Services, surfaces, and joinery sequence', 'Quality checks, snagging, and handover'], 'Timeline placeholder · programme issued after assessment', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85', ARRAY['building', 'finishing', 'coordination'], 4, TRUE),
('svc-05', '05', 'office-remodeling', 'Office Remodeling', 'Professional commercial renovation shaped around how your team works, meets, and grows.', 'Office Remodeling treats the workplace as a working system: clear circulation, durable finishes, focused lighting, and a professional atmosphere.', ARRAY['Layouts that slow collaboration or privacy', 'A workplace that no longer reflects the business', 'Poor lighting, flooring, partitions, or meeting flow'], ARRAY['Office aesthetics', 'Functional layouts', 'Finishes', 'Lighting', 'Flooring', 'Partitions', 'Professional appearance'], ARRAY['Workplace brief and existing-space review', 'Layout and finish direction', 'Phased delivery with operational considerations'], 'Timeline placeholder · phased programme after brief', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85', ARRAY['office', 'commercial', 'workplace'], 5, TRUE),
('svc-06', '06', 'rental-property-makeover', 'Rental Property Makeover', 'A practical uplift that improves appearance, functionality, and rental appeal.', 'Rental Property Makeover focuses on the changes that help a property feel ready: clean presentation, reliable function, and durable decisions.', ARRAY['A rental that is hard to present confidently', 'Small defects affecting tenant appeal', 'Rooms that need better use without overbuilding'], ARRAY['Appearance improvements', 'Functionality improvements', 'Tenant preparation', 'Rental appeal direction'], ARRAY['Condition review and priority list', 'Targeted repairs and visual uplift', 'Final styling check and ready-to-let handover'], 'Timeline placeholder · dependent on property condition', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85', ARRAY['rental', 'makeover', 'investment'], 6, TRUE),
('svc-07', '07', 'complete-home-remodeling', 'Complete Home Remodeling', 'A premium, whole-home transformation for new layouts, extensions, and elevated finishing.', 'Complete Home Remodeling is for a home that needs more than a surface update: a new spatial logic, a stronger material story, and careful delivery from structure to finish.', ARRAY['A home constrained by its existing layout', 'A need for extensions or structural change', 'Disconnected rooms, finishes, and services'], ARRAY['Structural changes', 'New layouts', 'Extensions', 'Luxury finishing'], ARRAY['Discovery, feasibility, and project brief', 'Design coordination and construction planning', 'Build, finish, snag, and handover'], 'Timeline placeholder · programme confirmed after feasibility', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85', ARRAY['remodel', 'extension', 'luxury'], 7, TRUE);

-- ============================================================================
-- PROJECTS
-- ============================================================================

INSERT INTO public.projects (id, title, slug, location, type, category, description, hero_image, before_images, during_images, after_images, services, service_slugs, materials, challenges, outcome, related_project_slugs, is_published) VALUES
('project-01', 'The Softened Arrival', 'the-softened-arrival', 'Maitama, Abuja', 'Residential renovation', ARRAY['Renovation', 'Interiors', 'Before & After'], 'A cooler, calmer entrance sequence for a family home with a heavy original layout.', '/manus-storage/concordvest-project_00304348.jpg', ARRAY['/manus-storage/concordvest-property_ef36ee68.jpg'], ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85'], ARRAY['/manus-storage/concordvest-project_00304348.jpg', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85'], ARRAY['Complete Home Remodeling', 'Home Refresh'], ARRAY['complete-home-remodeling', 'home-refresh'], ARRAY['Textured plaster', 'Warm oak', 'Brushed metal', 'Limestone-look porcelain'], ARRAY['Rebalance a dark arrival', 'Create storage without visual weight', 'Keep the home operational during works'], 'The entry, living spaces, and circulation now read as one quieter sequence—more generous, more useful, and easier to maintain.', ARRAY['the-everyday-kitchen', 'quiet-lines-warm-light'], TRUE),
('project-02', 'The Everyday Kitchen', 'the-everyday-kitchen', 'Jabi, Abuja', 'Kitchen transformation', ARRAY['Kitchens', 'Finishing', 'Before & After'], 'A working kitchen shaped around hosting, storage, and the unhurried parts of a day.', 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=1600&q=85', ARRAY['/manus-storage/concordvest-kitchen_fd650693.jpg'], ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85'], ARRAY['https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85'], ARRAY['Kitchen Transformation'], ARRAY['kitchen-transformation'], ARRAY['Oak veneer', 'Quartz composite', 'Hand-finished tile', 'Warm LED lighting'], ARRAY['Improve storage in a compact footprint', 'Hide service clutter', 'Make the kitchen feel connected to the living room'], 'A better working triangle, a more generous prep surface, and a finish palette that can handle daily life.', ARRAY['the-softened-arrival', 'material-made-precise'], TRUE),
('project-03', 'Quiet Lines, Warm Light', 'quiet-lines-warm-light', 'Asokoro, Abuja', 'Bathroom upgrade', ARRAY['Bathrooms', 'Finishing'], 'A compact bathroom brought into focus through proportion, light, and durable tactile finishes.', 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=85', ARRAY['/manus-storage/concordvest-property_ef36ee68.jpg'], ARRAY['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=85'], ARRAY['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85'], ARRAY['Luxury Bathroom Upgrade'], ARRAY['luxury-bathroom-upgrade'], ARRAY['Porcelain tile', 'Ribbed vanity front', 'Brushed brass', 'Microcement-look finish'], ARRAY['Work within existing service positions', 'Improve storage without shrinking the room', 'Introduce a calmer material story'], 'A more restful bathroom with better storage, cleaner detailing, and a finish that feels considered from every angle.', ARRAY['the-softened-arrival', 'the-everyday-kitchen'], TRUE),
('project-04', 'Material, Made Precise', 'material-made-precise', 'Wuse 2, Abuja', 'Commercial interior', ARRAY['Interiors', 'Finishing'], 'A workplace refresh that gives a growing team clearer zones for focus, exchange, and welcome.', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85', ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85'], ARRAY['https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85'], ARRAY['https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85'], ARRAY['Office Remodeling'], ARRAY['office-remodeling'], ARRAY['Acoustic slats', 'Resilient flooring', 'Powder-coated partitions', 'Layered lighting'], ARRAY['Work around a live office', 'Separate focus and meeting zones', 'Create a more professional client arrival'], 'The office now works harder without feeling crowded—clearer circulation, more useful partitions, and a more assured first impression.', ARRAY['the-softened-arrival', 'the-everyday-kitchen'], TRUE),
('project-05', 'The Open House', 'the-open-house', 'Gwarinpa, Abuja', 'Complete building finishing', ARRAY['Exterior', 'Finishing', 'Before & After'], 'A partially finished structure given a coherent exterior and a more resolved interior direction.', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85', ARRAY['/manus-storage/concordvest-property_ef36ee68.jpg'], ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85'], ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85'], ARRAY['Complete Building Finishing'], ARRAY['complete-building-finishing'], ARRAY['Stone-look cladding', 'Slimline aluminium', 'Terrazzo-inspired tile', 'Painted timber'], ARRAY['Coordinate multiple finishing trades', 'Create a stronger street presence', 'Bring unfinished services to a clear sequence'], 'A structure with a clearer point of view—finished from the outside in, with the sequence and details aligned.', ARRAY['material-made-precise', 'quiet-lines-warm-light'], TRUE);

-- ============================================================================
-- ARTICLES
-- ============================================================================

INSERT INTO public.articles (id, title, slug, category, excerpt, content, hero_image, read_time, date, service_slugs, project_slugs, property_link, is_published) VALUES
('article-01', 'Things to Inspect Before Moving Into a New Home', 'things-to-inspect-before-moving-into-a-new-home', 'Home Improvement Tips', 'A practical first walk-through for the details that shape comfort, maintenance, and peace of mind.', '[{"heading": "Start with the quiet systems", "body": "Before unpacking, move through the home slowly. Look for the things that are easy to ignore when a space is staged: water pressure, drainage, sockets, switches, doors, windows, and the way light moves through each room."}, {"heading": "Look closely at the finish", "body": "Small defects often point to larger maintenance questions. Check paint edges, tile joints, silicone lines, cabinet alignment, and areas where moisture gathers. Document what you find with photographs and a simple room-by-room list."}, {"heading": "Make the first month easier", "body": "A home does not need to be perfect on day one. It needs a clear priority list. Separate urgent safety or service issues from the improvements that can make the space feel more like yours over time."}]', '/manus-storage/concordvest-property_ef36ee68.jpg', '6 min read', '14 August 2026', ARRAY['home-refresh', 'complete-home-remodeling'], ARRAY['the-softened-arrival'], '/properties', TRUE),
('article-02', 'Which Kitchen Would You Choose?', 'which-kitchen-would-you-choose', 'Kitchen Inspiration', 'Three ways to think about the kitchen: as a working room, a social room, and a material composition.', 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=1600&q=85', '5 min read', '08 August 2026', ARRAY['kitchen-transformation'], ARRAY['the-everyday-kitchen'], NULL, TRUE),
('article-03', '5 Modern Staircase Ideas', '5-modern-staircase-ideas', 'Staircase Ideas', 'Five ways to make the stair feel less like a connector and more like a considered architectural moment.', 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85', '4 min read', '02 August 2026', ARRAY['complete-home-remodeling', 'complete-building-finishing'], ARRAY['the-softened-arrival'], NULL, TRUE),
('article-04', 'Painting Transformation', 'painting-transformation', 'Materials & Finishes', 'What changes when colour, sheen, preparation, and light are treated as one decision.', 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85', '5 min read', '25 July 2026', ARRAY['home-refresh'], ARRAY['the-softened-arrival', 'material-made-precise'], NULL, TRUE),
('article-05', 'Spa Bathroom Inspiration', 'spa-bathroom-inspiration', 'Bathroom Inspiration', 'A calmer bathroom usually begins with fewer, better decisions: proportion, texture, light, and storage.', 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=85', '5 min read', '18 July 2026', ARRAY['luxury-bathroom-upgrade'], ARRAY['quiet-lines-warm-light'], NULL, TRUE),
('article-06', 'Construction Mistakes Homeowners Should Avoid', 'construction-mistakes-homeowners-should-avoid', 'Construction Tips', 'A clear brief and a disciplined sequence can prevent the most expensive kind of rework.', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85', '7 min read', '10 July 2026', ARRAY['complete-building-finishing', 'complete-home-remodeling'], ARRAY['the-open-house'], NULL, TRUE);

-- ============================================================================
-- SAMPLE ADMIN USER (Create this manually in Supabase Auth)
-- ============================================================================
-- After creating the auth user, you can update their role:
-- UPDATE public.profiles SET role = 'admin' WHERE email = 'admin@concordvest.com';
